config/routes.rb
FacebookAuthExample::Application.routes.draw do
    get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'
    get 'public_keys', to: 'public_keys#index', as: 'public_keys'

    resources :sessions,  only: [:create, :destroy]
    resource  :home,      only: [:show]
    resources :games,     only: [:show, :create, :index]

    root to: "home#show"
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :users, foreign_key: :game_id
  belongs_to :creator, class_name: "User", foreign_key: :creator_id
end

app/models/user.rb
require 'base64'

class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.username = user.name
      user.base64_private_key = Base64.encode64(RbNaCl::PrivateKey.generate)
      user.base64_public_key =  Base64.encode64(RbNaCl::PrivateKey.new(Base64.decode64(user.base64_private_key)).public_key)
      user.save!
    end
  end

  def private_key
    @private_key ||= RbNaCl::PrivateKey.new(Base64.decode64(base64_private_key))
  end

  def public_key
    @public_key ||= private_key.public_key
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def require_login
    #grab the curretn path and sign them in then redirect where they inteded to origonally go
    redirect_to root_path unless current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :require_login

  def create
    @game = Game.create(creator_id: current_user.id)
    User.find(current_user.id).update(game_id: @game.id)
    redirect_to game_path(@game.id)
  end

  def show
    redirect_to root_path unless current_user.game_id = params[:id]
    @game = current_user
  end

  def index
    @games = Game.includes(:users).where("games.status = 'not_started'")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/public_keys_controller.rb
class PublicKeysController < ApplicationController
  def index
    @users = User.select(:username, :base64_public_key)
  end

  # def create
  #   user = User.find(session[:user_id])
  #   if user
  #     PublicKey.create(user_id: user.id, text: params[:text])
  #   end
  # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/games/index.html.erb
<ul>
  <% @games.each do |game| %>
    <li>
      <button>join <%= game.creator.username %>'s Game </button>
    </li>
  <% end %>
</ul>

app/views/games/show.html.erb
<% %>

app/views/home/show.html.erb
<% if current_user %>
  <h1>Generate a Key</h1>
  <button id="key_creation_button">Create</button>
  <div id="key_data"></div>
<% else %>
  <h1>Welcome. Please Log In Above</h1>
<% end %>


<%= form_for :game, url: games_path do |f| %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FacebookAuthExample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  Intended for fun only. Do not use for real security applications
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <!--
      Below we include the Login Button social plugin. This button uses
      the JavaScript SDK to present a graphical Login button that triggers
      the FB.login() function when clicked.
    -->
    <fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
    </fb:login-button>

    <div id="status">
    </div>

    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
    <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
  <% end %>

  <nav>
    <%= link_to "Public Keys", public_keys_path, id: "public_keys" %>
  </nav>
</div>
<%= yield %>

</body>
</html>

app/views/public_keys/index.html.erb
<h1>ALL PUBLIC KEYS</h1>
<p>Your public key and everyone else's can and should be published. Here is the list of everyones public key who plays this game:</p>

<ol>
  <% @users.each do |user| %>
    <li>
      <%= "#{user.username}" %> : <%= "#{user.base64_public_key}" %>
    </li>
  <% end %>
</ol>